framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - App\Middleware\ReleaseRecordedEventsMiddleware
                    - doctrine_transaction
            query.bus:
                middleware: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: failed
                    queues:
                        failed: ~
            process-charge-batch-file:
                serializer: messenger.transport.symfony_serializer
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: process-charge-batch-file
                options:
                    exchange:
                        name: process-charge-batch-file
                    queues:
                        process-charge-batch-file: ~
            process-charge:
                serializer: messenger.transport.symfony_serializer
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: process-charge
                options:
                    exchange:
                        name: process-charge
                    queues:
                        process-charge: ~
            email:
                serializer: messenger.transport.symfony_serializer
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: email
                options:
                    exchange:
                        name: email
                    queues:
                        email: ~

        routing:
            'DDD\Model\ChargeBatchFile\Command\ProcessChargeBatchFileCommand': process-charge-batch-file
            'DDD\Model\Charge\Command\SaveChargeCommand': process-charge
            'DDD\Model\Charge\Command\SendChargeSavedEmailNotificationCommand': email

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
