version: '3.2'

services:
  php:
    build:
      context: "../back"
      dockerfile: "../env/php/Dockerfile"
    expose:
      - "9000"
    ports:
      - "9000:9000"
    links:
      - rabbitmq:rabbitmq
      - postgres:postgres
    volumes:
      - ../back:/app
      - ./php/supervisord.conf:/etc/supervisord.conf
    restart: unless-stopped
    networks:
      - symfony_ddd

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - symfony_ddd
    links:
      - php:php

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      DEFAULT_USER: ddd
      DEFAULT_PASS: '1234'
    networks:
      - symfony_ddd
    expose:
      - '5672'
    ports:
      - '15672:15672'
      - '5672:5672'

  postgres:
    image: 'postgres:16-alpine'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: ddd
      POSTGRES_DB: ddd
    restart: unless-stopped
    networks:
      - symfony_ddd

networks:
  symfony_ddd:

